Csabamotor.Web/Models/CsabamotorDBContext.cs
using Microsoft.EntityFrameworkCore;

namespace Csabamotor.Web.Models
{
    public class CsabamotorDBContext : DbContext
    {
        public DbSet<List> Lists { get; set; } = null!;
        public DbSet<Item> Items { get; set; } = null!;

        public CsabamotorDBContext(DbContextOptions<CsabamotorDBContext> options)
            : base(options)
        {
        }
    }
}

Csabamotor.Web/Models/DbInitializer.cs
using Microsoft.EntityFrameworkCore;

namespace Csabamotor.Web.Models
{
    public static class DbInitializer
    {
        public static void Initialize(CsabamotorDBContext context, string imageDirectory)
        {
            // Use only one of the below.
            // Create / update database based on migration classes.

            //context.Database.Migrate();
            // Create database if not exists based on current code-first model (no migrations!).
            context.Database.EnsureCreated();

            if (context.Lists.Any())
            {
                return;
            }

            string ScooterPath = Path.Combine(imageDirectory, "sampleScooter.jpg");
            string WheelPath = Path.Combine(imageDirectory, "fakerek.jpg");

            IList<List> defaultLists = new List<List>
            {
                new List
                {
                    Name = "Robogók",
                    Items = new List<Item>()
                    {
                        new Item()
                        {
                            Name = "Honda Term-Inátór",
                            Price=100000,
                            Description = "Megkíméletlen állapot",
                            UploadTime = DateTime.Now,
                            Image = File.Exists(ScooterPath) ? File.ReadAllBytes(ScooterPath) : null

                        },
                        new Item()
                        {
                            Name = "To Yoda",
                            Price=150000,
                            Description = "Megkíméletlen állapot",
                            UploadTime = DateTime.Now,
                            Image = File.Exists(ScooterPath) ? File.ReadAllBytes(ScooterPath) : null
                        },
                    }
                },
                new List
                {
                    Name = "Alkatrészek",
                    Items = new List<Item>()
                    {
                        new Item()
                        {
                            Name = "Fakerék",
                            Price = 5000,
                            Description = "Megbízható tüzelőanyag!",
                            UploadTime = DateTime.Now,
                            Image = File.Exists(WheelPath) ? File.ReadAllBytes(WheelPath) : null
                        }
                    }
                }
            };

            context.AddRange(defaultLists);
            context.SaveChanges();
        }
    }
}

Csabamotor.Web/Models/ErrorViewModel.cs
namespace Csabamotor.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Csabamotor.Web/Models/Item.cs
using System.ComponentModel.DataAnnotations;

namespace Csabamotor.Web.Models
{
    public class Item
    {
        [Key]
        public Int32 Id { get; set; }

        public String Name { get; set; } = null!;
        [DataType(DataType.MultilineText)]
        public String? Description { get; set; }
        public UInt32 Price { get; set; }
        public DateTime UploadTime { get; set; }

        public byte[]? Image { get; set; }
        public Int32 ListId { get; set; }
        public virtual List List { get; set; } = null!;
    }
}

Csabamotor.Web/Models/List.cs
using System.ComponentModel.DataAnnotations;

namespace Csabamotor.Web.Models
{
    public class List
    {
        public List()
        {
            Items = new HashSet<Item>();
        }

        [Key]
        public Int32 Id { get; set; }

        [MaxLength(30)]
        public String Name { get; set; } = null!;

        public virtual ICollection<Item> Items { get; set; }
    }
}

Csabamotor.Web/Controllers/HomeController.cs
using Csabamotor.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Csabamotor.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Csabamotor.Web/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Csabamotor.Web.Models;
using Csabamotor.Web.Services;

namespace Csabamotor.Web.Controllers
{
    public class ItemsController : Controller
    {
        private readonly ICsabamotorService _service;

        public ItemsController(ICsabamotorService service)
        {
            _service = service;
        }

        public IActionResult? DisplayImage(int id)
        {
            var item = _service.GetItem(id);
            if (item != null && item.Image != null)
            {
                return File(item.Image, "image/jpg");
            }
            return null;
        }
    }
}

Csabamotor.Web/Controllers/ListsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Csabamotor.Web.Models;
using Csabamotor.Web.Services;
using Microsoft.Data.SqlClient;

namespace Csabamotor.Web.Controllers
{
    public class ListsController : Controller
    {
        private readonly ICsabamotorService _service;

        public ListsController(ICsabamotorService service)
        {
            _service = service;
        }

        // GET: Lists
        public IActionResult Index()
        {
            return View(_service.GetLists());
        }

        // GET: Lists/Details/5
        public IActionResult Details(int id)
        {
            try
            {
                //ViewData["NameSortParam"] = sortOrder == SortOrder.NAME_DESC ? SortOrder.NAME_ASC : SortOrder.NAME_DESC;
                //ViewData["DeadLineSortParam"] = sortOrder == SortOrder.DEADLINE_DESC ? SortOrder.DEADLINE_ASC : SortOrder.DEADLINE_DESC;

                List list = _service.GetListDetails(id);

                //switch (sortOrder)
                //{
                //    case SortOrder.NAME_DESC:
                //        list.Items = list.Items.OrderByDescending(i => i.Name).ToList();
                //        break;
                //    case SortOrder.NAME_ASC:
                //        list.Items = list.Items.OrderBy(i => i.Name).ToList();
                //        break;
                //    case SortOrder.DEADLINE_DESC:
                //        list.Items = list.Items.OrderByDescending(i => i.Deadline).ToList();
                //        break;
                //    case SortOrder.DEADLINE_ASC:
                //        list.Items = list.Items.OrderBy(i => i.Deadline).ToList();
                //        break;
                //    default:
                //        break;
                //}

                return View(list);
            }
            catch (InvalidOperationException)
            {
                return NotFound();
            }
        }
    }
}

Csabamotor.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Navigate to <a asp-controller="Lists">Csabamotor</a>.</p>
</div>

Csabamotor.Web/Views/Items/Create.cshtml
@model Csabamotor.Web.Models.Item

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Item</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UploadTime" class="control-label"></label>
                <input asp-for="UploadTime" class="form-control" />
                <span asp-validation-for="UploadTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ListId" class="control-label"></label>
                <select asp-for="ListId" class ="form-control" asp-items="ViewBag.ListId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Csabamotor.Web/Views/Items/Delete.cshtml
@model Csabamotor.Web.Models.Item

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Item</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UploadTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UploadTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.List)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.List.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Csabamotor.Web/Views/Items/Details.cshtml
@model Csabamotor.Web.Models.Item

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Item</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UploadTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UploadTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.List)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.List.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Csabamotor.Web/Views/Items/Edit.cshtml
@model Csabamotor.Web.Models.Item

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Item</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UploadTime" class="control-label"></label>
                <input asp-for="UploadTime" class="form-control" />
                <span asp-validation-for="UploadTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ListId" class="control-label"></label>
                <select asp-for="ListId" class="form-control" asp-items="ViewBag.ListId"></select>
                <span asp-validation-for="ListId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Csabamotor.Web/Views/Items/Index.cshtml
@model IEnumerable<Csabamotor.Web.Models.Item>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UploadTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Image)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.List)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UploadTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Image)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.List.Id)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Csabamotor.Web/Views/Lists/Details.cshtml
@model Csabamotor.Web.Models.List

@{
    ViewData["Title"] = "Details";
}

<h1>@Html.DisplayFor(model => model.Name)</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                Image
            </th>
            <th>
                <a asp-action="Details">Name</a>
            </th>
            <th>
                Description
            </th>
            <th>
                Price
            </th>
            <th>
                <a asp-action="Details">Date</a>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Items)
        {
            <tr>
                <td>
                    @if (item.Image != null)
                    {
                        <img src="@Url.Action("DisplayImage", "Items", new { id = item.Id })" class="item" />
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price) Ft
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UploadTime)
                </td>
            </tr>
        }
    </tbody>
</table>
<a asp-action="Index">Back to list</a>

Csabamotor.Web/Views/Lists/Index.cshtml
@model IEnumerable<Csabamotor.Web.Models.List>

@{
    ViewData["Title"] = "Index";
}

<h1>Termékek</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
            </td>
        </tr>
}
    </tbody>
</table>

Csabamotor.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Csabamotor</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Csabamotor.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Csabamotor</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Lists" asp-action="Index">Termékek</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Csabamotor.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>